### ISSUE TITLE
pcangsd and other figures data

### ISSUE THREAD

**Issue by ThomasDesvignes** [sudmantlab/loco-pipe#7]
Hi,
I've been using loco-pipe and so far really appreciate it! Thanks!
The only thing is that I have hard time finding the underlying data for several plots. For example, in my pcangsd global combined.subsetted plot (see below the 2 main PC), I can tell that few individuals have likely been misidentified in the first place (red among the blue circles and blue among the red circles) and I'd like to go back to the actual specimen to double check the ID, but I can't find the data for the plot that could tell me which specimen is which one... There's also one specimen that is obviously an outlier (top left one) that I'd like to take out.
![Screenshot 2024-12-03 091050](https://github.com/user-attachments/assets/9b4f08a8-d9fe-4d4b-bffb-b72462d4f64f)
Similarly, I have a few specimens that are strong outliers in the heterozygocity plot and I'd like to take them out but I can't tell which dot is which specimen...
Probably a dumb question but I've searched through all the files that locopipe generated and I can't find those data. Can you point those to me?
Thanks again!
Thomas

**Comment by nicolas931010** [comment]
Hi @ThomasDesvignes , 

Thank you very much for your feedback! These intermediate data tables are currently not outputted by loco-pipe, so you may need to use some of the R scripts [here](https://github.com/sudmantlab/loco-pipe/tree/main/workflow/scripts) to put them together yourself. It's a good idea to output these data, however, and I will add it to my list of to-dos. 

Best,
Nicolas

**Comment by nicolas931010** [comment]
Hi @ThomasDesvignes,

I agree and have just [updated the pipeline](https://github.com/sudmantlab/loco-pipe/commit/9b7019a504623d10b0a57bfc9691eebbd0842057) to output the data tables used for plotting depth distribution, heterozygosity, PCA, and admixture analysis. If you have a chance to give it a try, please let me know whether it works as intended. Thank you!

Best,
Nicolas

**Comment by ThomasDesvignes** [comment]
Awesome! Thanks!
I updated the eight files and just started a run on a single chromosome. I should have the results later today. I will look into the new output tables and let you know if that returns what I have in mind.
Thanks again!
Thomas

**Comment by ThomasDesvignes** [comment]
Hi @nicolas931010,
So my analysis went through in just a few hours (I didn't ask for the Ohana test because it is meaningless with this dataset). 
For the heterozygosity and the pcangsd local, it's perfect and the new tsv files that it creates is exactly what I needed!

But the pcangsd_global failed, and no plot nor {basedir}\figures\pcangsd\global folder were created. In the {basedir}\pcangsd\global folder, there seems to be all the needed files (.cov, .done, .log, .plot, .sites, and .weight), but no .tsv file like in the {basedir}\pcangsd\local folder. 
Comparing ".subsetted.log" files between previous run that worked and this new one that didn't produce a global pca, the change is after the line "ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message." when it says "Error in `filter()`:

Rows: 58 Columns: 4
── Column specification ────────────────────────────────────────────────────────
Delimiter: "\t"
chr (4): sample_name, bam, sex, population

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Error in `filter()`:
ℹ In argument: `get(pop_col) == pop`.
Caused by error in `get()`:
! object 'pop_col' not found
Backtrace:
     ▆
  1. ├─read_tsv(sample_table_path) %>% filter(get(pop_col) == pop)
  2. ├─dplyr::filter(., get(pop_col) == pop)
  3. ├─dplyr:::filter.data.frame(., get(pop_col) == pop)
  4. │ └─dplyr:::filter_rows(.data, dots, by)
  5. │   └─dplyr:::filter_eval(...)
  6. │     ├─base::withCallingHandlers(...)
  7. │     └─mask$eval_all_filter(dots, env_filter)
  8. │       └─dplyr (local) eval()
  9. ├─base::get(pop_col)
 10. └─base::.handleSimpleError(...)
 11.   └─dplyr (local) h(simpleError(msg, call))
 12.     └─rlang::abort(message, class = error_class, parent = parent, call = error_call)
Execution halted

In my previous run, after the line "ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.", it just went on with: 
Rows: 58 Columns: 58
── Column specification ────────────────────────────────────────────────────────
Delimiter: " "
dbl (58): X1, X2, X3, X4, X5, X6, X7, X8, X9, X10, X11, X12, X13, X14, X15, ...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Warning message:
In get_plot_component(plot, "guide-box") :
  Multiple components found; returning the first one. To return all, use `return_all = TRUE`.


And it finished seemingly without issues.

I didn't modify any of my input files between the two runs, just updated the folders names.
Any idea what's going on?
Let me know if I can provide any other file or parts to troubleshoot.
Thanks!

**Comment by nicolas931010** [comment]
Hi @ThomasDesvignes,

Thank you so much for reporting this bug. I just pushed an update that hopefully fixes this. Please let me know whether it works for you.

Best,
Nicolas

**Comment by ThomasDesvignes** [comment]
Hi @nicolas931010 ,
It fixed it! Thank you! Now I can easily correct my specimen assignment and hopefully gain in resolution at the same time.
Thomas
